name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions: 
      contents: write  # ✅ Grants permission to write to the repo

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: PathToPrecision
          outputs: dist/github-contribution-grid-snake.svg

      - name: Move Generated Snake
        run: |
          sudo mkdir -p assets
          sudo mv dist/github-contribution-grid-snake.svg assets/github-contribution-grid-snake.svg
          sudo chmod 777 assets/github-contribution-grid-snake.svg  # Grant full permissions


      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/github-contribution-grid-snake.svg
          git commit -m "Updated snake animation"
          git push
